apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  namespace: nzdev-org-homepage
  name: homepage-image-repo
spec:
  image: asskit/nzdev-org
  interval: 5m
  secretRef:
    name: homepage-registry
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  namespace: nzdev-org-homepage
  name: homepage-image-policy
spec:
  imageRepositoryRef:
    name: homepage-image-repo
    namespace: nzdev-org-homepage
  filterTags:
    pattern: '^build-(?P<timesamp>.*)$'
    extract: '$timestamp'
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: nzdev-org-homepage
  namespace: homepage-image-automation
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: nzdev-org-homepage
  git:
    commit:
      author:
        email: fluxcdbot@nzdev.org
        name: fluxcdbot
    push:
      branch: main
  update:
    path: ./
