name: Docker imagiser

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  check-user:
    runs-on: ubuntu-latest
    steps:
      - name: Check if user is allowed
        id: check
        run: |
          if [ "${GITHUB_ACTOR}" == "fluxcdbot" ]; then
            echo "User ${GITHUB_ACTOR} is not allowed to trigger this workflow."
            exit 1
          else
            echo "User ${GITHUB_ACTOR} is allowed to trigger this workflow."
          fi

  
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: TimeTag
        run: echo "TIME_TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/nzdev-org
          tags: |
            # branch event
            type=ref,enable=false,priority=600,prefix=,suffix=,event=branch
            # tag event
            type=ref,enable=true,priority=600,prefix=,suffix=,event=tag
            # pull request event
            type=ref,enable=true,priority=600,prefix=pr-,suffix=,event=pr

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ secrets.DOCKERHUB_USERNAME }}/nzdev-org:build-${{ env.TIME_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
